### ISSUE TITLE
Bot Not Exist...

### ISSUE THREAD

**Issue by baneeishaque** [ihavenonickname/bot-telegram-comentarios-xvideos#2]
Bot **@comentarios_xvideos_bot** Not Exist...

**Comment by ihavenonickname** [comment]
Are you sure? 

![image](https://user-images.githubusercontent.com/8087298/62828118-e3b04c00-bbb4-11e9-8152-121edc09c729.png)

**Comment by baneeishaque** [comment]
![Screenshot_20190811-082658](https://user-images.githubusercontent.com/6133009/62829040-61567500-bc12-11e9-8a5b-18d756204620.jpg)

Tried in telegram plus.
